Added opponent board.
EECS-581-Cool-Kids/Project1-Battleship pull request #11
Opened 2024-09-05 02:35 UTC by modmo22

Major changes:

- Increased window width to 1000 to fit both windows
- Created helper functions from pre-existing logic to reduce redundant logic in executing identical logic for each grid object
- Tweaked mouse handling and draw logic to account for two boards.

Embedded video demos game behavior. Hovering behavior is distinct for both grids, left- and right-clicking perform miss and hit behaviors, respectively (not the final behavior, but works according to the default logic).

https://github.com/user-attachments/assets/2090b005-a8d2-4297-80e1-d3ef88997ba5

2024-09-05 02:49 UTC, jacobwilki01 requested changes
Looks fine for the previous version of develop, but since develop has changed a lot you'll need to merge it in and make changes respectively.

2024-09-05 02:49 UTC, jacobwilki01 commented on Battleship/BattleshipGame.cs
> +        /// Two internal grid objects. One for player and one for opponent.
Instead of storing this under one comment, separate it and make it two comments.

When you use the /// summary formatting, it creates an object comment that shows up whenever you hover over the name of the object.

2024-09-05 02:49 UTC, jacobwilki01 commented on Battleship/BattleshipGame.cs
> +        private void LoadGridTextures(Grid _grid, string _gridOwner)
Delete this method and merge in the current develop branch. it has this moved to the Grid object itself. you should just have to call _playerGrid.LoadContent() and _opponentGrid.LoadContent().

2024-09-05 02:49 UTC, jacobwilki01 commented on Battleship/BattleshipGame.cs
> +        private void HandleGridInteraction(Grid _grid, Vector2 _position)
Same with this method, it's handled in the Grid class now in develop.

2024-09-05 02:49 UTC, jacobwilki01 commented on Battleship/BattleshipGame.cs
> +        private void DrawGrid(Grid _grid, Vector2 postition)
This method as well.

2024-09-05 02:49 UTC, jacobwilki01 commented on Battleship/BattleshipGame.cs
> +            LoadGridTextures(_opponentGrid, "opponent");
Instead of passing in a string to identify who "owns" the grid, move it to a property within the Grid class itself.

Something like:
public int PlayerNum { get; set; }

would be sufficient. Then you can just pass in 1 or 2 into the constructor for a Grid.

2024-09-05 03:08 UTC, jacobwilki01 commented on Battleship/BattleshipGame.cs
> +        private Grid _opponentGrid;
call this _player2Grid instead, because we technically have two possible players and not a player vs opponent.

2024-09-05 18:30 UTC, modmo22 commented on Battleship/BattleshipGame.cs
> +        /// Two internal grid objects. One for player and one for opponent.
So, are you saying that it should be two different comment lines within the ///<summary></summary> formatting?

2024-09-05 18:32 UTC, jacobwilki01 commented on Battleship/BattleshipGame.cs
> +        /// Two internal grid objects. One for player and one for opponent.
Yes. Like all of the other objects throughout the code, separate comment for each object.

2024-09-05 23:59 UTC, jacobwilki01 requested changes

2024-09-05 23:59 UTC, jacobwilki01 commented on Battleship/BattleshipGame.cs
> +        /// <summary>
dont need constructor comments

2024-09-05 23:59 UTC, jacobwilki01 commented on Battleship/BattleshipGame.cs
> +        private void HandleGridInteraction(Grid _grid, Vector2 _position)
This method is unused. Remove it and make sure the changes in here (i.e., how the mousePoint is calculated) is reflected within the Grid.cs version of the method.

2024-09-05 23:59 UTC, jacobwilki01 commented on Battleship/BattleshipGame.cs
> +        private void DrawGrid(Grid _grid, Vector2 postition)
Just like the above, this method is unused. Remove it and make sure the functionality is moved to Grid.cs.

2024-09-05 23:59 UTC, jacobwilki01 commented on Battleship/BattleshipGame.cs
> +        private Grid _player1grid;
Do this instead.
![image](https://github.com/user-attachments/assets/1ab4830c-f22a-4b04-a324-be8130ec044e)

2024-09-05 23:59 UTC, jacobwilki01 commented on Battleship/Grid.cs
> +            this.playerNum = Interlocked.Increment(ref _playerCounter); // Increment the player counter and assign the value to playerNum. Thread-safe.
As discussed in the general channel of discord, this is unnecessary.

2024-09-06 00:00 UTC, jacobwilki01 commented on Battleship/Grid.cs
> +        /// The
finish comment (but we dont need this so you can just remove it.

2024-09-06 00:25 UTC, modmo22 commented on Battleship/BattleshipGame.cs
> +        private void LoadGridTextures(Grid _grid, string _gridOwner)
These errors with the dead code are because of my unsuccessful attempt at resolving my local branches after accidentally writing on my local develop branch. I'll make sure that they're not included.

2024-09-06 00:49 UTC, modmo22 commented on Battleship/BattleshipGame.cs
> +        private Grid _player1grid;
Ah, I understand more clearly what you meant about the object-comment pairing, now. Thanks!

2024-09-06 01:12 UTC, modmo22 commented on Battleship/BattleshipGame.cs
> +        /// <summary>
Tell me more about this -- is there a convention re: constructor code comments? Or is it just redundant?

2024-09-06 02:04 UTC, jacobwilki01 approved these changes

2024-09-09 00:56 UTC, richardmoser approved these changes
Send it

2024-09-09 13:21 UTC, merged