Feature ship art
EECS-581-Cool-Kids/Project1-Battleship pull request #20
Opened 2024-09-11 00:33 UTC by richardmoser

ship and cursor art as well as ship art rotation functionality should all work now.

2024-09-11 02:34 UTC, modmo22 approved these changes
There is some overlap on the right side of both grids with the horizontal cursor. I tried to find what the issue could be in the code, but didn't see anything that jumped out at me. When you place a ship while the cursor overlaps, it does get placed on the appropriate grid without leaving the grid boundaries. I think for the sake of time, we leave the bug for the next team to fix, or for down the line. We've got a lot of tickets to get into PR by Thursday, and I don't think this bug is worth delaying the approval of this PR.

2024-09-11 02:36 UTC, jacobwilki01 commented
Add the .idea folder and all files you added to the .gitignore file.

2024-09-11 02:43 UTC, jacobwilki01 requested changes

2024-09-11 02:43 UTC, jacobwilki01 commented on Battleship/Grid.cs
> +        // private const int SQUARE_SIZE = 9;
Remove commented out code

2024-09-11 02:43 UTC, jacobwilki01 commented on Battleship/GridTile.cs
> +        // private const int SQUARE_SIZE = 9;
Remove

2024-09-11 02:43 UTC, jacobwilki01 commented on Battleship/GridTile.cs
> +
remove white space

2024-09-11 02:43 UTC, jacobwilki01 commented on Battleship/GridTile.cs
> +            int xAdjust = - SCALE * SQUARE_SIZE * shipSize + SCALE * SQUARE_SIZE / 2 - 3;
move the 2 and 3 to constants and name them.

also, add a comment what this math is doing. im confused.

2024-09-11 02:43 UTC, jacobwilki01 commented on Battleship/GridTile.cs
> +            int yAdjust = - SCALE * SQUARE_SIZE * shipSize + SCALE * SQUARE_SIZE / 2 - 3;
same as above on xAdjust

2024-09-11 02:43 UTC, jacobwilki01 commented on Battleship/ShipManager.cs
> +        // private const int SQUARE_SIZE = 9;
remove

2024-09-11 02:43 UTC, jacobwilki01 commented on Battleship/ShipManager.cs
>          public Texture2D? ShipTexture1x5 { get; set; }
lets rename these to add Horizontal

2024-09-11 02:43 UTC, jacobwilki01 commented on Battleship/ShipManager.cs
> +        public Texture2D? ShipTexture1x1vert { get; set; }
spell out vertical. Also, Pascal case so ShipTexture1x1Vertical

2024-09-11 02:43 UTC, jacobwilki01 commented on Battleship/ShipManager.cs
>              ShipTexture1x5 = content.Load<Texture2D>("ship1x5");
Lets rename the texture files as well. More clarity is better

2024-09-11 02:43 UTC, jacobwilki01 commented on Battleship/ShipManager.cs
> +
remove white space

2024-09-11 02:43 UTC, jacobwilki01 commented on Battleship/ShipManager.cs
> +                        1 => ShipTexture1x1,
remove the case for 1. we already have "default" running to it, so it is unneeded.

2024-09-11 02:43 UTC, jacobwilki01 commented on Battleship/ShipManager.cs
> +                        1 => ShipTexture1x1vert,
remove the case for 1, like above

2024-09-11 02:43 UTC, jacobwilki01 commented on Battleship/BattleshipGame.cs
> +        private const int PLAYER_2_OFFSET = 880; // should be SQUARE_SIZE * GRID_SIZE * 2 * SCALE, i.e. 16 * 11 * 2 * scale / 2
Like discussed in the Discord, let's go ahead and move this plus other constant ints to a static class, make them public, and reference those throughout the file.

2024-09-13 02:51 UTC, jacobwilki01 requested changes

2024-09-13 02:51 UTC, jacobwilki01 commented on Battleship/static.cs
Class name should be capital. It should also be named constants.

2024-09-13 02:51 UTC, jacobwilki01 commented on Battleship/static.cs
> +    public class Static
```suggestion
    public static class Constants
```

Static is a modifier to class type. Not the name for it. A static class is one that does NOT require instantiation, i.e., it is not an object that can be created. They are also values loaded at start time, meaning they are available at the START of the program.

2024-09-13 02:51 UTC, jacobwilki01 commented on Battleship/BattleshipGame.cs
> +        private const int PLAYER_2_OFFSET = 880; // should be SQUARE_SIZE * GRID_SIZE * 2 * SCALE, i.e. 16 * 11 * 2 * scale / 2
move this to Constants.cs.

2024-09-13 02:51 UTC, jacobwilki01 commented on Battleship/BattleshipGame.cs
> +            _graphics.PreferredBackBufferWidth = 1760; // should be SQUARE_SIZE * GRID_SIZE * 2 * SCALE, i.e. 16 * 11 * 2 * scale
instead of commenting the math just do the math as the size then it is always adjusting correctly. Especially in a world where we are saving the constants in a static class.

2024-09-13 02:51 UTC, jacobwilki01 commented on Battleship/BattleshipGame.cs
> +            _graphics.PreferredBackBufferHeight = 880; // should be SQUARE_SIZE * GRID_SIZE * SCALE, i.e. 16 * 11 * scale
same here

2024-09-13 02:51 UTC, jacobwilki01 commented on Battleship/Grid.cs
> +        private const int SQUARE_SIZE = Static.SQUARE_SIZE;
nope. this just obviates the point of having a static class like that. Instead of changing THIS instance, delete it and change all of the REFERENCES throughout this class to the Constants.cs class.

you did that in GridTile lol so not sure why you didn't here.

2024-09-13 02:51 UTC, jacobwilki01 commented on Battleship/Grid.cs
> +        private const int SCALE = Static.SCALE;
same here

2024-09-13 02:51 UTC, jacobwilki01 commented on Battleship/GridTile.cs
> +
remove whitespace after return

2024-09-13 02:51 UTC, jacobwilki01 commented on Battleship/GridTile.cs
remove whitespace after return.

2024-09-13 02:51 UTC, jacobwilki01 commented on Battleship/ShipManager.cs
> +        public Texture2D? ShipTexture1x1Horizontal{ get; set; }
space between object name and squiggly bracket.

2024-09-13 02:51 UTC, jacobwilki01 commented on Battleship/ShipManager.cs
> +        public Texture2D? ShipTexture1x1vertical { get; set; }
Pascal case, so ShipTexture1x1Vertical.

2024-09-13 02:51 UTC, jacobwilki01 commented on Battleship/ShipManager.cs
> +            ShipTexture1x1Horizontal= content.Load<Texture2D>("ship1x1horizontal");
add space between object name and equals sign.

2024-09-13 02:51 UTC, jacobwilki01 commented on Battleship/ShipManager.cs
> +                switch (orientation)
if the switch case makes the code longer, an if statement is sufficient. revert this. you should only use switch cases when there are a ton of values to compare to because it just creates a br assembly instruction. in this case, C# enums are just fancy masks for ints so it's the same time complexity.

2024-09-13 03:42 UTC, jacobwilki01 approved these changes

2024-09-13 03:42 UTC, jacobwilki01 commented on Battleship/Battleship.csproj
> +    <Folder Include="Documentation\" />
remove this folder and add it in the relevant ticket

2024-09-13 03:42 UTC, jacobwilki01 commented on Battleship/BattleshipGame.cs
> +
remove extra line

2024-09-13 03:42 UTC, jacobwilki01 commented on Battleship/Constants.cs
> +        public const int PLAYER_2_OFFSET = 880; // should be SQUARE_SIZE * GRID_SIZE * 2 * SCALE, i.e. 16 * 11 * 2 * scale / 2
move this comment at the end to a new line in the summary comment above

2024-09-13 03:42 UTC, jacobwilki01 commented on Battleship/Constants.cs
> +        ///<summary>
```suggestion
        /// <summary>
```

2024-09-13 03:42 UTC, jacobwilki01 commented on Battleship/Grid.cs
> +        private const int SQUARE_SIZE = Constants.SQUARE_SIZE;
you need to remove these. I said this before lol. update the references to SQUARE_SIZE and TILE_SIZE like you did in the other class.

2024-09-13 03:42 UTC, jacobwilki01 commented on Battleship/ShipManager.cs
remove whitespace between squiggly and comment

2024-09-13 03:46 UTC, merged